name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: go-url-shortener

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .
        
    - name: Test Docker image
      run: |
        # Start the container in the background
        docker run -d --name test-container -p 8080:8080 ${{ env.IMAGE_NAME }}:latest
        
        # Wait a moment for the container to start
        sleep 5
        
        # Test health endpoint
        curl -f http://localhost:8080/healthz || exit 1
        
        # Clean up
        docker stop test-container
        docker rm test-container